# Generated by Django 3.0 on 2019-12-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='repo_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=160)),
                ('location', models.CharField(max_length=160)),
                ('github_link', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('github_username', models.CharField(max_length=160)),
                ('repo_name', models.CharField(max_length=160)),
            ],
        ),
    ]
