# Generated by Django 3.0 on 2019-12-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191208_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo_info',
            name='github_username',
        ),
        migrations.RemoveField(
            model_name='repo_info',
            name='repo_name',
        ),
        migrations.AddField(
            model_name='repo_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
