# Generated by Django 3.0 on 2019-12-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191212_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
